-
  title: Typical build (combined and compressed)
  build: true
  compare: _expected/standard _site
-
  title: Configure stylesheets_dir
  build: true
  config:
    jekyll:
      - _config.yml
      - _configure_css_dir.yml
  compare: _expected/configure_css_dir _site
-
  title: Configure stylesheets_dir
  build: true
  config:
    jekyll:
      - _config.yml
      - _configure_js_dir.yml
  compare: _expected/configure_js_dir _site
-
  title: Combine CSS only
  build: true
  config:
    jekyll:
      - _config.yml
      - _combine_css_only.yml
  compare: _expected/css_tag_only _site
-
  title: Separate asset files
  build: true
  config: 
    jekyll:
      - _config.yml
      - _combine_false.yml
  compare: _expected/no_combining _site
