-
  title: Typical build (combined and compressed)
  build: true
  compare: _expected/standard _site
-
  title: Combine CSS only
  build: true
  config:
    jekyll:
      - _config.yml
      - _combine_css_only.yml
  compare: _expected/css_tag_only _site
-
  title: Separate asset files
  build: true
  config: 
    jekyll:
      - _config.yml
      - _combine_false.yml
  compare: _expected/no_combining _site
